name: Check iStoreOS Version
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get and compare version
      id: version_check
      run: |
        # 获取当前版本
        curl -s "https://fw21.koolcenter.com:60010/iStoreOS/armsr/version.index" > current_version.txt
        current_version=$(cat current_version.txt)
        echo "当前版本: $current_version"
        
        # 检查版本是否变化
        if [ -f last_version.txt ] && [ "$current_version" = "$(cat last_version.txt)" ]; then
          echo "版本未变化"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "版本已变化: $(cat last_version.txt 2>/dev/null || echo '无') -> $current_version"
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "$current_version" > last_version.txt
          
          # 保存版本并提交
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add last_version.txt
          git commit -m "更新到版本 $current_version"
          git push
        fi

    - name: Trigger workflows
      if: steps.version_check.outputs.changed == 'true'
      run: |
        # 触发sync-files工作流
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/sync-files.yml/dispatches \
          -d '{"ref":"main"}'
        echo "已触发sync-files工作流"
        
        # 等待2分钟后触发testbuild工作流
        echo "等待2分钟..."
        sleep 120
        
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/testbuild-istoreos-6.x.yml/dispatches \
          -d '{"ref":"main"}'
        echo "已触发testbuild-istoreos-6.x工作流"
